---
ruby:
  enabled: true
  config_file: ".rubocop.yml"
eslint:
  enabled: true
  config_file: ".eslintrc.json"
tslint:
  enabled: true
  config_file: tslint.json
scss:
  enabled: true
  config_file: ".scss-lint.yml"
