---
version: '3.4'
services:
  test:
    build:
      context: "."
      dockerfile: Dockerfile.ci
    volumes:
    - "test_data:/usr/local/bundle"
    environment:
      RACK_ENV: test
      DB_USER: postgres
      DB_HOST: postgresql
      DB_PORT: '5432'
    links:
    - postgresql
  postgresql:
    image: postgres:9.4.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ''
volumes:
  test_data:
