---
  version: '3'
  services:
    postgresql:
      image: postgres:11.3
      ports:
      - 5432
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: ''
      volumes:
      - postgresql_data:/var/lib/postgresql/data
    redis:
      image: redis
      ports:
        - 6379
      volumes:
        - redis_data:/data
  volumes:
    postgresql_data:
    redis_data: