---
version: '3'
services:
  postgresql:
    image: postgres:9.4.5
    ports:
    - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ''
    volumes:
    - postgresql_data:/var/lib/postgresql/data
volumes:
  postgresql_data:
