/* eslint-disable import/prefer-default-export */
export const COMPUTE_RECOMMENDATIONS = 'COMPUTE_RECOMMENDATIONS';
export const PROCESS_NEW_TEAM = 'PROCESS_NEW_TEAM';

export const UPDATE_DEFAULT_TEAM = 'UPDATE_DEFAULT_TEAM';

export const CREATE_NEW_FROGGO_TEAM = 'CREATE_NEW_FROGGO_TEAM';
export const UPDATE_FROGGO_TEAM = 'UPDATE_FROGGO_TEAM';
export const DELETE_FROGGO_TEAM = 'DELETE_FROGGO_TEAM';
export const COMPUTE_PROFILE_PR_INFORMATION = 'COMPUTE_PROFILE_PR_INFORMATION';
export const COMPUTE_TEAM_PR_INFORMATION = 'COMPUTE_TEAM_PR_INFORMATION';

export const LOAD_DEFAULT_PREFERENCES = 'LOAD_DEFAULT_PREFERENCES';

export const LOAD_RECOMMENDATIONS = 'LOAD_RECOMMENDATIONS';
