/* eslint-disable import/prefer-default-export */
export const COMPUTE_SCORES = 'COMPUTE_SCORES';
export const COMPUTE_STATISTICS = 'COMPUTE_STATISTICS';
export const COMPUTE_RECOMMENDATIONS = 'COMPUTE_RECOMMENDATIONS';
export const PROCESS_NEW_TEAM = 'PROCESS_NEW_TEAM';

export const UPDATE_DEFAULT_TEAM = 'UPDATE_DEFAULT_TEAM';
