/* eslint-disable import/prefer-default-export */
export const COMPUTE_SCORES = 'COMPUTE_SCORES';
export const COMPUTE_STATISTICS = 'COMPUTE_STATISTICS';
export const COMPUTE_RECOMMENDATIONS = 'COMPUTE_RECOMMENDATIONS';
export const PROCESS_NEW_TEAM = 'PROCESS_NEW_TEAM';

export const UPDATE_DEFAULT_TEAM = 'UPDATE_DEFAULT_TEAM';

export const CREATE_NEW_FROGGO_TEAM = 'CREATE_NEW_FROGGO_TEAM';
export const COMPUTE_PROFILE_PR_INFORMATION = 'COMPUTE_PROFILE_PR_INFORMATION';
export const CREATE_NEW_FROGGO_TEAM = 'CREATE_NEW_FROGGO_TEAM';
