export const USER_SCORE_START_FETCHING = 'USER_SCORE_START_FETCHING';
export const USER_SCORE_RECEIVED = 'USER_SCORE_RECEIVED';
export const USER_SCORE_FETCH_ERROR = 'USER_SCORE_FETCH_ERROR';

export const PROFILE_TEAM_SELECTED = 'PROFILE_TEAM_SELECTED';
export const PROFILE_ORGANIZATION_SELECTED = 'PROFILE_ORGANIZATION_SELECTED';
export const START_FETCHING_RECOMMENDATIONS = 'START_FETCHING_RECOMMENDATIONS';
export const RECOMMENDATIONS_RECEIVED = 'RECOMMENDATIONS_RECEIVED';
export const RECOMMENDATIONS_FETCH_ERROR = 'RECOMMENDATIONS_FETCH_ERROR';
export const ORGANIZATION_TEAMS_RECEIVED = 'ORGANIZATION_TEAMS_RECEIVED';
