export const USER_SCORE_START_FETCHING = 'USER_SCORE_START_FETCHING';
export const USER_SCORE_RECEIVED = 'USER_SCORE_RECEIVED';
export const USER_SCORE_FETCH_ERROR = 'USER_SCORE_FETCH_ERROR';

export const USER_STATISTICS_START_FETCHING = 'USER_STATISTICS_START_FETCHING';
export const USER_STATISTICS_RECEIVED = 'USER_STATISTICS_RECEIVED';
export const USER_STATISTICS_FETCH_ERROR = 'USER_STATISTICS_FETCH_ERROR';

export const PROFILE_TEAM_SELECTED = 'PROFILE_TEAM_SELECTED';
export const START_FETCHING_RECOMMENDATIONS = 'START_FETCHING_RECOMMENDATIONS';
export const RECOMMENDATIONS_RECEIVED = 'RECOMMENDATIONS_RECEIVED';
export const RECOMMENDATIONS_FETCH_ERROR = 'RECOMMENDATIONS_FETCH_ERROR';

export const START_FETCHING_PR_INFORMATION = 'START_FETCHING_PR_INFORMATION';
export const PROFILE_PR_INFORMATION_RECEIVED = 'PROFILE_PR_INFORMATION_RECEIVED';
export const PROFILE_PR_INFORMATION_FETCH_ERROR = 'PROFILE_PR_INFORMATION_FETCH_ERROR';

export const TEAM_NAME = 'TEAM_NAME';
