export const SCORE_FETCH_ERROR = 'SCORE_FETCH_ERROR';
export const SCORE_RECEIVED = 'SCORE_RECEIVED';
export const SCORE_START_FETCHING = 'SCORE_START_FETCHING';

export const CREATE_PUBLIC_USER_ENTRY = 'CREATE_PUBLIC_USER_ENTRY';
export const PUBLIC_USER_SCORE_START_FETCHING = 'PUBLIC_USER_SCORE_START_FETCHING';
export const PUBLIC_USER_SCORE_RECEIVED = 'PUBLIC_USER_SCORE_RECEIVED';
export const PUBLIC_USER_SCORE_FETCH_ERROR = 'PUBLIC_USER_SCORE_FETCH_ERROR';
