production:
  :concurrency: <%= ENV.fetch('SIDEKIQ_CONCURRENCY', 5) %>
:queues:
  - default
:schedule:
  #  an_scheduled_task:
  #    cron: '0 * * * * *'  # Runs once per minute
  #    class: ExampleJob
  #    args: ['a', 'b']
