production:
  :concurrency: <%= ENV.fetch('SIDEKIQ_CONCURRENCY', 5) %>
:queues:
  - default
  - pull_requests
  - reviews
:limits:
    pull_requests: 2
    reviews: <%= [ENV.fetch('SIDEKIQ_CONCURRENCY', 5).to_i - 2, 1].max %>
:schedule:
  #  an_scheduled_task:
  #    cron: '0 * * * * *'  # Runs once per minute
  #    class: ExampleJob
  #    args: ['a', 'b']
